### ISSUE TITLE
Calendar need some love [meta issue]

### ISSUE THREAD

**Issue by philippejadin** [agorakit/agorakit#303]
- [x] remove the list view
- [x] remember preferred calendar view (and date?) in a session/cookie
- [x] allow user to create event by clicking on calendar
- [x] allow user to change event start end time by dragging : https://fullcalendar.io/docs/editable / https://fullcalendar.io/docs/eventDrop
- [x] logical order of views : day / week / month / 6 months (or year?) / list

This can all be done with the fullcalendar lib currently in use.
