### ISSUE TITLE
Membership revamp [meta issue]

### ISSUE THREAD

**Issue by philippejadin** [agorakit/agorakit#340]
Taken from here : https://app.agorakit.org/groups/39/discussions/5335

- [ ] Better member list
- no datatable, simple unpoly dynamic form
- simple search (keyword + dropdown with various status (with count of each category)) ->  unpoly autosubmit form
- edit button (for group admins)
- xls export
- show various status, put above all members in need of validation
- show pseudo
- number of messages / events / files posted

- [ ] Hide emails except for super admins (configurable)

- [ ] membership history (revisionable) + link for admins to check it

- [ ] candidates can provide a motivation text when asking to join a group
- add this text to admin notifications (stored in membership table)

- [ ] Membership edit screen (for group admins)
- radio buttons with all status + description

- [ ] check membership workflow
- blacklisted user can't join a group anymore (policy)
- admin can't re-invite user declined (?)

**Comment by philippejadin** [comment]
Sur ecran edit membership : 

-    Type de membre (invité, normal, admin, blacklisté)
-   Retirer du groupe (le membre pourra revenir dans le groupe si il le souhaite / sinon il faut le blacklister)
-    Renvoyer une invitation (si statut "invité)
-    Notifications : instantané, toutes les heures, tous les jours, toutes les semaines, tous les mois

https://app.agorakit.org/groups/39/discussions/4583
